### Request to Azure API

GET https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=a526481a-064e-477f-bc0d-54f88ef4c7b5&scope=api://a526481a-064e-477f-bc0d-54f88ef4c7b5/Files.note
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjlHbW55RlBraGMzaE91UjIybXZTdmduTG83WSIsImtpZCI6IjlHbW55RlBraGMzaE91UjIybXZTdmduTG83WSJ9.eyJhdWQiOiJodHRwczovL29uZW5vdGUuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvODNlYzAzZmQtMmRjZS00ZWI1LWEwYTgtMzA5OGJmZTEyYjU3LyIsImlhdCI6MTY5NzQxNTYyMiwibmJmIjoxNjk3NDE1NjIyLCJleHAiOjE2OTc0MTk1MjIsImFpbyI6IkUyRmdZR2l3ZXBtZ2tCV1JHYXZZLzdSSjRyY1RBQT09IiwiYXBwaWQiOiJhNTI2NDgxYS0wNjRlLTQ3N2YtYmMwZC01NGY4OGVmNGM3YjUiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC84M2VjMDNmZC0yZGNlLTRlYjUtYTBhOC0zMDk4YmZlMTJiNTcvIiwib2lkIjoiY2Q4NTlkYmMtYWIzZC00ZDY1LWI3
Content-Type: application/json


